/*
 * generated by Xtext
 */
package com.ihaomo.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TypesUiModule extends com.ihaomo.language.ui.AbstractTypesUiModule {
	public TypesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
