/*
 * generated by Xtext
 */
package com.ihaomo.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FunctionsRuntimeModule extends com.ihaomo.language.AbstractFunctionsRuntimeModule {

}
