/*
* generated by Xtext
*/
package com.ihaomo.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FunctionsStandaloneSetup extends FunctionsStandaloneSetupGenerated{

	public static void doSetup() {
		new FunctionsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

