/*
 * generated by Xtext
 */
package com.ihaomo.language.ui.contentassist

import com.ihaomo.language.ui.contentassist.AbstractFunctionsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FunctionsProposalProvider extends AbstractFunctionsProposalProvider {
}
