/*
 * generated by Xtext
 */
package com.ihaomo.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FunctionsUiModule extends com.ihaomo.language.ui.AbstractFunctionsUiModule {
	public FunctionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
