/*
 * generated by Xtext
 */
package com.ihaomo.language.ui.contentassist

import com.ihaomo.language.ui.contentassist.AbstractTypesProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TypesProposalProvider extends AbstractTypesProposalProvider {
}
